services:
    mercari-bot:
        build:
            context: .
            dockerfile: Dockerfile
        tty: false
        stdin_open: true
        volumes:
            - ./data:/opt/mercari-bot/data
