services:
    mercari-bot:
        image: ghcr.io/kimata/mercari-bot:latest
        tty: false
        stdin_open: true
        volumes:
            - ./config.yaml:/opt/mercari-bot/config.yaml:ro
            - ./data:/opt/mercari-bot/data
